name: Build and push to Ecr

on:
  push:
    branches:
      - master

jobs:
  login_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Amazon Ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login To Amazon Ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY_URL: 402788687549.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY_NAME: ecr-eks-workflow-repo
      run: |
        docker build -t $ECR_REGISTRY_URI/$ECR_REPOSITORY_NAME:latest .
        docker push -a $ECR_REGISTRY_URI/$ECR_REPOSITORY_NAME

  Use EKS:
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.28.2'
      id: install

    - name: Update kube config
      run: aws eks update-kubeconfig --name cluster-two --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f deploy.yml -f service.yml




