name: Build and push to Ecr

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: diogohudson/build_docker_2_ecr_eks@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: ecr-eks-cicd
        region: us-east-1
        tags: latest
        image_scanning_configuration: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json
        cluster_name: my-great-cluster-name
        kubectl_command: apply -f kubernetes/service.yml
